- hosts: all
  become: yes

  vars_files:
   - vars/default.yml

  roles:
    - { role: geerlingguy.repo-epel, tags: ["epel"] }
    - { role: environment, tags: ["environment"] }
    - { role: tomcat, tags: ["tomcat"] }
    - { role: shibboleth-idp, tags: ["shibboleth-idp"] }
    - { role: httpd, tags: ["httpd"] }
    - { role: shibboleth-sp, tags: ["shibboleth-sp"] }
    - { role: openldap, tags: ["openldap"] }
    - { role: totp-authenticator, tags: ["totp-authenticator"] }
    - { role: posttasks, tags: ["posttasks"] }
