---
download_dir: /opt/download
tomcat_unixgroup: tomcat
tomcat_unixgid: 1000
tomcat_unixuser: tomcat
tomcat_unixuid: 1000
tomcat_installdir: /opt
tomcat_servicename: tomcat
shib_idp_version: 3.2.0
shib_installdir: /opt
shib_home: "{{ shib_installdir }}/shibboleth-idp/"
jdk_download_path: 'http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08'
jdk_download_file: 'jdk-8u172-linux-x64.tar.gz'
java_installdir: /opt
java_version: 1.8.0_172
maven_installdir: /opt
tomcat_version: 8.0.30
totp_installdir: /opt
totp_version: 0.5.1
ldap_url: "ldap://localhost:389"
ldap_base_dn: ou=People,dc=vagrant,dc=local
ldap_manager: cn=manager,dc=vagrant,dc=local
ldap_password: Password1
